apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-volume
  labels:
    type: local
    app: database
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/fzo-kube/database/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-volume-claim
  namespace: fzo-data
  labels:
    app: database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi