apiVersion: apps/v1
kind: Deployment
metadata:
  name: fzo-frontend
  namespace: fzo-frontend
  labels:
    app: fzo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fzo-frontend
  template:
    metadata:
      labels:
        app: fzo-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/do3-2023/fzo-kube/frontend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 2
