apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fzo-frontend
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - port: 80
      targetPort: http